<template>
  <section class="taumaturgia-section">
    <div class="container">
      <!-- Título principal -->
      <div class="row">
        <div class="col-xl-12">
          <div class="main-title text-center mb-5">
            <h1>TAUMATURGIA (EVENTOS MÁGICOS)</h1>
          </div>
        </div>
      </div>

      <!-- Sección PRESAGIO -->
      <div class="presagio-section">
        <div class="row">
          <div class="col-xl-12">
            <div class="section-title text-center mb-5">
              <h2>PRESAGIO</h2>
            </div>
          </div>
        </div>

        <!-- Calendario placeholder -->
        <div class="calendar-container">
          <div class="calendar-header">
            <h3 id="currentMonth"></h3>
            <div class="calendar-nav">
              <button id="prevMonth">&lt;</button>
              <button id="nextMonth">&gt;</button>
            </div>
          </div>
          <div class="calendar-grid" id="calendar">
            <!-- Calendar will be generated by JavaScript -->
          </div>
        </div>
      </div>

      <!-- Sección Encuentros ceremoniales y rituales -->
      <div class="encuentros-section mt-5">
        <div class="row">
          <div class="col-xl-12">
            <div class="section-title text-center mb-5">
              <h2>Encuentros ceremoniales y rituales</h2>
              <p class="subtitle">En este enlace describimos los eventos que organizamos, los cuales te especificamos a continuación ☺</p>
            </div>
          </div>
        </div>

        <!-- Evento Principal - Reino Fungi -->
        <div class="row mb-5">
          <div class="col-xl-12">
            <div class="evento-card evento-card-principal">
              <div class="evento-icon">
                <img src="/assets/images/Servicios/Reino_fungi.png" alt="Reino Fungi" class="emblema emblema-principal">
              </div>
              <h3>MEDICINA DEL REINO FUNGI</h3>

              <div class="fungi-variants-grid">
                <div class="variant-item">
                  <h4>"ENCANTAMIENTO"</h4>
                  <p>Encuentro Ritual de conexión con las energías elementales y las fuerzas naturales, con la ingesta de una dosis ritual de setas psilocibicas deshidratadas, rezos de intención, rueda medicinal, oráculos, cantos, icaros y música de medicina en vivo, en un espacio de Naturaleza, en presencia del Fuego Ceremonial, que constituye el altar principal. Finaliza con círculo de palabra y de acompañamiento terapéutico.</p>
                </div>

                <div class="variant-item">
                  <h4>FUNGI "HECHIZO"</h4>
                  <p>Encuentro Ritual de conexión con las energías elementales y las fuerzas naturales, con la ingesta de una dosis ritual profunda de setas psilocibicas deshidratadas, rezos de intención, rueda medicinal, oráculos, cantos, icaros y música de medicina en vivo, en un espacio de Naturaleza, en presencia del Fuego Ceremonial, que constituye el altar principal. Finaliza con círculo de palabra y de acompañamiento terapéutico.</p>
                </div>

                <div class="variant-item">
                  <h4>"CONJURO"</h4>
                  <p>Encuentro Ritual exclusivo para estudiosos y caminantes de esta medicina, de conexión con las energías elementales y las fuerzas naturales, con la ingesta de una dosis ritual super profunda de setas psilocibicas deshidratadas, rezos de intención, rueda medicinal, oráculos, cantos, icaros y música de medicina en vivo, en un espacio de Naturaleza, en presencia del Fuego Ceremonial, que constituye el altar principal. Finaliza con círculo de palabra y de acompañamiento terapéutico.</p>
                </div>

                <div class="variant-item">
                  <h4>RESONANCIA MÁGICA MEDITATIVA</h4>
                  <p>Círculo de meditación, con la ingesta de una dosis meditativa/sensorial de setas psilocibicas deshidratadas, acompañado de sonidos vibratorios orgánicos y música meditativa en vivo, para el despertar sensorial del propio ser, induciendo a la calma y al encuentro consigo mismo, bien como un primer acercamiento a la Medicina del Reino Fungi, o para entrar en una meditación profunda, mientras se reciben los beneficios biológicos de esta medicina (4 horas).</p>
                </div>

                <div class="variant-item variant-item-centered">
                  <h4>RESONANCIA MÁGICA MUSICAL</h4>
                  <p>Círculo medicinal contemplativo, acompañado de música de medicina, con la ingesta de una dosis meditativa/sensorial de setas psilocibicas deshidratadas, para desplegar estados favorables en el despertar de la creatividad, la armonía interna, la alegría y la expresión del ser a través de la danza, la pintura, la escritura y la participación musical, mientras se reciben los beneficios biológicos de esta medicina. (5 horas).</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Eventos Secundarios -->
        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-12 mb-4">
            <div class="evento-card evento-card-large">
              <div class="evento-icon">
                <img src="/assets/images/Servicios/YageAyahuasca.png" alt="Medicina Ancestral de la Selva" class="emblema">
              </div>
              <h3>MEDICINA ANCESTRAL DE LA SELVA</h3>
              <p>Encuentro chamánico grupal, con la ingesta de esta Planta de Poder, que emplea la energía ancestral y la conexión con las fuerzas elementales, acompañado de rezos, rueda medicinal, armonización energética, cantos, icaros y música de medicina en vivo, en un espacio de Naturaleza, en presencia del Fuego Ceremonial. Finaliza con círculo de palabra y de acompañamiento terapéutico.</p>
            </div>
          </div>

          <div class="col-xl-6 col-lg-6 col-md-12 mb-4">
            <div class="evento-card evento-card-large">
              <div class="evento-icon">
                <img src="/assets/images/Servicios/Teramai_Senchen.png" alt="Reiki Teramai" class="emblema">
              </div>
              <h3>REIKI TERAMAI – SEICHEM (REIKI ESTILO CHAMÁNICO)</h3>
              <p>Formación grupal y proceso iniciático de canalización energética de los rayos de sanación de la Tierra, el Agua, el Aire y el Fuego. Manejo de la energía angelical, la sanación con colores, la armonía vibracional, la danza chamánica y el canto curativo. Formación en 6 Niveles: 2 Niveles de Formación Reiki Teramai-Seiche; 3 Niveles de Magia Teramai y Maestría.</p>
            </div>
          </div>

          <div class="col-xl-4 col-lg-4 col-md-6 mb-4">
            <div class="evento-card evento-card-medium">
              <div class="evento-icon">
                <img src="/assets/images/Servicios/Abra_Cadabra.png" alt="Abra Cadabra" class="emblema emblema-medium">
              </div>
              <h3>ABRA CADABRA</h3>
              <p>Compartir grupal y de aprendizaje, a través de la palabra, guiado con actividades creativas y dinámicas grupales que permiten desarrollar la conciencia del aquí y ahora en los procesos individuales, así como el incremento de la comunicación amorosa. (2 horas).</p>
            </div>
          </div>

          <div class="col-xl-4 col-lg-4 col-md-6 mb-4">
            <div class="evento-card evento-card-medium">
              <div class="evento-icon">
                <img src="/assets/images/icon/sesiones.png" alt="Sesiones" class="emblema emblema-medium">
              </div>
              <h3>SESIONES</h3>
              <p>Recital de Música de Medicina, con la participación de varios músicos invitados, a través del cual se genera un espacio de esparcimiento que emplea la música como medio de conciencia. (4 horas).</p>
            </div>
          </div>

          <div class="col-xl-4 col-lg-4 col-md-6 mb-4">
            <div class="evento-card evento-card-medium">
              <div class="evento-icon">
                <img src="/assets/images/Servicios/MagicSaDan.png" alt="MagicsaDan" class="emblema emblema-medium">
              </div>
              <h3>MAGICSADAN</h3>
              <p>Sesiones grupales de sagrado movimiento mágico ancestral; movimiento auténtico y consciente de efectos terapéuticos, combinando danza sagrada y rituales de poder, que permiten reconectar con nuestra fuerza vital primordial, nuestra naturaleza divina. Herramienta de auto conocimiento, que regula el bienestar, disminuye el cortisol en el cuerpo producto del estrés y permite la conexión del individuo con su biología, su esencia, la consciencia de estar vivo, la Magia que portamos y la sacralidad en todo, en la existencia misma.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { onMounted } from 'vue'

onMounted(() => {
  initCalendar()
})

const initCalendar = () => {
  const monthNames = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
  ]

  // Eventos del calendario Presagio
  const events = [
    {
      date: new Date(2025, 9, 18), // 18 Oct 2025 (mes 9 = octubre)
      title: 'MEDICINA FUNGI',
      subtitle: 'ENCUENTRO CEREMONIAL NOCTURNO',
      location: 'Los Teques',
      type: 'fungi',
      logo: '/assets/images/Servicios/Reino_fungi.png'
    },
    {
      date: new Date(2025, 9, 22), // 22 Oct 2025
      title: 'MAGICSADAN',
      subtitle: 'MOVIMIENTO MÁGICO ANCESTRAL',
      location: 'Los Ruíces, Caracas',
      type: 'magicsadan',
      logo: '/assets/images/Servicios/MagicSaDan.png',
      recurring: true,
      nextDate: new Date(2025, 10, 5) // 05 Nov 2025
    },
    {
      date: new Date(2025, 10, 1), // 01 Nov 2025 (mes 10 = noviembre)
      title: 'VELADA MÁGICA MUSICAL',
      subtitle: 'CELEBRANDO EL LANZAMIENTO DE MAGIANCESTRAL.COM',
      location: 'Bello Monte, Caracas',
      type: 'velada',
      logo: '/assets/images/Servicios/Velada_Musical.png'
    },
    {
      date: new Date(2025, 10, 5), // 05 Nov 2025
      title: 'MAGICSADAN',
      subtitle: 'MOVIMIENTO MÁGICO ANCESTRAL',
      location: 'Los Ruíces, Caracas',
      type: 'magicsadan',
      logo: '/assets/images/Servicios/MagicSaDan.png'
    },
    {
      date: new Date(2025, 10, 15), // 15 Nov 2025
      title: 'MEDICINA ANCESTRAL DE LA SELVA',
      subtitle: 'ENCUENTRO CEREMONIAL NOCTURNO',
      location: 'Los Teques',
      type: 'ayahuasca',
      logo: '/assets/images/Servicios/YageAyahuasca.png'
    },
    {
      date: new Date(2025, 10, 29), // 29 Nov 2025
      title: 'TERAMAI - SEICHEM',
      subtitle: 'FORMACIÓN EN REIKI Y MAGIA SHAMÁNICA',
      location: 'Bello Monte, Caracas',
      type: 'teramai',
      logo: '/assets/images/Servicios/Teramai_Senchen.png',
      multiDay: true,
      endDate: new Date(2025, 10, 30) // 30 Nov 2025
    },
    {
      date: new Date(2025, 10, 30), // 30 Nov 2025
      title: 'TERAMAI - SEICHEM',
      subtitle: 'FORMACIÓN EN REIKI Y MAGIA SHAMÁNICA',
      location: 'Bello Monte, Caracas',
      type: 'teramai',
      logo: '/assets/images/Servicios/Teramai_Senchen.png'
    }
  ]

  let currentMonth = new Date().getMonth()
  let currentYear = new Date().getFullYear()

  const updateCalendar = () => {
    const monthElement = document.getElementById('currentMonth')
    const calendarElement = document.getElementById('calendar')

    if (!monthElement || !calendarElement) return

    monthElement.textContent = `${monthNames[currentMonth]} ${currentYear}`

    // Clear calendar
    calendarElement.innerHTML = ''

    // Days of week header
    const daysOfWeek = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']
    daysOfWeek.forEach(day => {
      const dayElement = document.createElement('div')
      dayElement.classList.add('calendar-day-header')
      dayElement.textContent = day
      calendarElement.appendChild(dayElement)
    })

    // Get first day of month and number of days
    const firstDay = new Date(currentYear, currentMonth, 1).getDay()
    const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate()

    // Add empty cells for days before first day of month
    for (let i = 0; i < firstDay; i++) {
      const emptyDay = document.createElement('div')
      emptyDay.classList.add('calendar-day', 'empty')
      calendarElement.appendChild(emptyDay)
    }

    // Add days of month
    for (let day = 1; day <= daysInMonth; day++) {
      const dayElement = document.createElement('div')
      dayElement.classList.add('calendar-day')

      // Número del día
      const dayNumber = document.createElement('div')
      dayNumber.classList.add('day-number')
      dayNumber.textContent = day
      dayElement.appendChild(dayNumber)

      // Check if there's an event on this day
      const currentDate = new Date(currentYear, currentMonth, day)
      const event = events.find(e =>
        e.date.getDate() === day &&
        e.date.getMonth() === currentMonth &&
        e.date.getFullYear() === currentYear
      )

      if (event) {
        dayElement.classList.add('has-event', `event-${event.type}`)
        dayElement.setAttribute('data-event', JSON.stringify(event))

        // Crear contenedor interno para el contenido
        const innerContent = document.createElement('div')
        innerContent.classList.add('day-content')

        // Mover el dayNumber al contenedor interno
        innerContent.appendChild(dayNumber)

        // Agregar indicador de evento
        const eventIndicator = document.createElement('div')
        eventIndicator.classList.add('event-indicator')
        eventIndicator.textContent = '●'
        innerContent.appendChild(eventIndicator)

        dayElement.appendChild(innerContent)

        // Información del evento (inicialmente oculta)
        const eventInfo = document.createElement('div')
        eventInfo.classList.add('event-info')
        eventInfo.style.display = 'none'
        eventInfo.innerHTML = `
          <div class="event-title">${event.title}</div>
          <div class="event-subtitle">${event.subtitle}</div>
          <div class="event-location">${event.location}</div>
        `
        dayElement.appendChild(eventInfo)

        // Click handler para mostrar/ocultar información
        dayElement.addEventListener('click', () => {
          // Cerrar todas las demás event-info
          document.querySelectorAll('.event-info').forEach(info => {
            if (info !== eventInfo) {
              info.style.display = 'none'
            }
          })
          // Toggle this event info
          eventInfo.style.display = eventInfo.style.display === 'none' ? 'block' : 'none'
        })
      } else {
        // Para días sin eventos, solo agregar el número
        const innerContent = document.createElement('div')
        innerContent.classList.add('day-content')
        innerContent.appendChild(dayNumber)
        dayElement.appendChild(innerContent)
      }

      calendarElement.appendChild(dayElement)
    }
  }

  // Navigation buttons
  const prevButton = document.getElementById('prevMonth')
  const nextButton = document.getElementById('nextMonth')

  if (prevButton) {
    prevButton.addEventListener('click', () => {
      currentMonth--
      if (currentMonth < 0) {
        currentMonth = 11
        currentYear--
      }
      updateCalendar()
    })
  }

  if (nextButton) {
    nextButton.addEventListener('click', () => {
      currentMonth++
      if (currentMonth > 11) {
        currentMonth = 0
        currentYear++
      }
      updateCalendar()
    })
  }

  updateCalendar()
}
</script>

<style scoped>
.taumaturgia-section {
  padding: 80px 0;
  background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
}

.main-title h1 {
  font-size: 4rem;
  color: #b3a85a;
  font-weight: 700;
  margin-bottom: 40px;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1);
}

.section-title h2 {
  font-size: 3rem;
  color: #b3a85a;
  font-weight: 700;
  margin-bottom: 20px;
}

.section-title .subtitle {
  font-size: 1.2rem;
  color: #6c757d;
  margin-bottom: 0;
}

.presagio-section {
  background: white;
  padding: 60px 40px;
  border-radius: 20px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
  margin-bottom: 60px;
}

/* Calendar Styles */
.calendar-container {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  border-radius: 15px;
  padding: 30px;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
  position: relative;
}

.calendar-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
}

.calendar-header h3 {
  font-size: 2rem;
  color: #b3a85a;
  font-weight: 600;
  margin: 0;
}

.calendar-nav button {
  background: #b3a85a;
  color: white;
  border: none;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  font-size: 1.2rem;
  cursor: pointer;
  transition: all 0.3s ease;
}

.calendar-nav button:hover {
  background: #7da052;
  transform: scale(1.1);
}

.calendar-grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 8px;
  margin-bottom: 20px;
}

.calendar-day-header {
  padding: 15px 10px;
  text-align: center;
  font-weight: 600;
  color: #b3a85a;
  border-bottom: 2px solid #e9ecef;
}

.calendar-day {
  width: 100%;
  height: 0;
  padding-bottom: 100%;
  position: relative;
  border-radius: 8px;
  transition: all 0.3s ease;
  cursor: pointer;
  border: 1px solid #e9ecef;
  background: white;
}

.calendar-day:not(.empty):hover {
  background: #f8f9fa;
}

.calendar-day.empty {
  cursor: default;
  background: #f8f9fa;
  border: 1px solid transparent;
}

.day-content {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 8px;
}

.day-number {
  position: absolute;
  top: 5px;
  left: 5px;
  font-weight: 600;
  color: #495057;
  font-size: 0.9rem;
  line-height: 1;
}

.event-indicator {
  font-size: 2rem;
  color: #b3a85a;
  line-height: 1;
}

.has-event {
  background: #fffef5;
  border: 2px solid #b3a85a;
  cursor: pointer;
}

.has-event:hover {
  background: #fff9e6;
  border-color: #7da052;
  z-index: 50;
}

.has-event .day-number {
  color: #b3a85a;
  font-weight: 700;
  font-size: 0.95rem;
}

.has-event:hover .event-indicator {
  color: #7da052;
  transform: scale(1.2);
  transition: all 0.3s ease;
}

.event-info {
  position: absolute;
  top: calc(100% + 10px);
  left: 50%;
  transform: translateX(-50%);
  padding: 12px;
  background: white;
  border-radius: 10px;
  border: 2px solid #b3a85a;
  box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);
  animation: fadeIn 0.3s ease;
  z-index: 1000;
  min-width: 220px;
  max-width: 280px;
  white-space: normal;
}

.event-info::before {
  content: '';
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-50%);
  border: 8px solid transparent;
  border-bottom-color: #b3a85a;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.event-title {
  font-weight: 700;
  font-size: 0.75rem;
  color: #b3a85a;
  margin-bottom: 5px;
  text-transform: uppercase;
  text-align: center;
}

.event-subtitle {
  font-size: 0.65rem;
  color: #6c757d;
  line-height: 1.3;
  margin-bottom: 5px;
  text-align: center;
}

.event-location {
  font-size: 0.7rem;
  color: #7da052;
  font-weight: 600;
  text-align: center;
}

/* Prevent calendar from shifting */
.presagio-section {
  position: relative;
  overflow: visible;
}

.calendar-container {
  overflow: visible;
}

.calendar-grid {
  overflow: visible;
}

/* Eventos Cards */
.encuentros-section {
  background: white;
  padding: 60px 40px;
  border-radius: 20px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);
}

.evento-card {
  background: white;
  padding: 40px 30px;
  border-radius: 15px;
  box-shadow: 0 8px 25px rgba(0, 0, 0, 0.1);
  text-align: center;
  transition: all 0.3s ease;
  height: 100%;
  border: 2px solid transparent;
}

.evento-card:hover {
  transform: translateY(-10px);
  box-shadow: 0 15px 40px rgba(179, 168, 90, 0.3);
  border-color: #b3a85a;
}

.evento-icon {
  margin-bottom: 25px;
}

.emblema {
  width: 80px;
  height: 80px;
  object-fit: contain;
  filter: opacity(0.8);
  transition: all 0.3s ease;
}

.evento-card:hover .emblema {
  filter: opacity(1);
  transform: scale(1.1);
}

.evento-card h3 {
  font-size: 1.8rem;
  color: #b3a85a;
  font-weight: 600;
  margin-bottom: 20px;
}

.evento-card p {
  color: #6c757d;
  line-height: 1.6;
  font-size: 1rem;
}

/* Cards más grandes para eventos principales */
.evento-card-large {
  padding: 50px 40px;
}

.evento-card-large h3 {
  font-size: 2rem;
  margin-bottom: 30px;
}

.evento-card-large p {
  font-size: 1.1rem;
  line-height: 1.7;
}

/* Variantes del Reino Fungi */
.fungi-variants {
  margin-top: 25px;
}

.variant-item {
  margin-bottom: 20px;
  padding: 20px;
  background: #f8f9fa;
  border-radius: 10px;
  border-left: 4px solid #b3a85a;
}

.variant-item:last-child {
  margin-bottom: 0;
}

.variant-item h4 {
  color: #b3a85a;
  font-size: 1.3rem;
  font-weight: 600;
  margin-bottom: 10px;
}

.variant-item p {
  margin-bottom: 0;
  font-size: 0.95rem;
}

/* Card Principal para Reino Fungi */
.evento-card-principal {
  background: linear-gradient(135deg, #ffffff 0%, #f8f9fa 100%);
  padding: 60px 50px;
  border: 3px solid #b3a85a;
  border-radius: 25px;
  box-shadow: 0 15px 40px rgba(179, 168, 90, 0.2);
}

.evento-card-principal h3 {
  font-size: 2.5rem;
  text-align: center;
  margin-bottom: 40px;
}

.emblema-principal {
  width: 120px;
  height: 120px;
  margin: 0 auto 30px;
  display: block;
}

.fungi-variants-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 25px;
  margin-top: 30px;
}

.fungi-variants-grid .variant-item {
  background: white;
  border: 2px solid #e9ecef;
  transition: all 0.3s ease;
}

.fungi-variants-grid .variant-item:hover {
  border-color: #b3a85a;
  transform: translateY(-3px);
  box-shadow: 0 8px 25px rgba(179, 168, 90, 0.15);
}

.variant-item-centered {
  grid-column: 1 / -1;
  max-width: 600px;
  margin: 0 auto;
}

/* Cards pequeñas */
.evento-card-small {
  padding: 25px 20px;
  background: white;
  border-radius: 12px;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);
  transition: all 0.3s ease;
  border: 1px solid #e9ecef;
}

.evento-card-small:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 25px rgba(179, 168, 90, 0.2);
  border-color: #b3a85a;
}

.evento-card-small h4 {
  font-size: 1.4rem;
  color: #b3a85a;
  font-weight: 600;
  margin-bottom: 15px;
}

.evento-card-small p {
  font-size: 0.9rem;
  line-height: 1.5;
  color: #6c757d;
  margin-bottom: 0;
}

.emblema-small {
  width: 50px;
  height: 50px;
  margin-bottom: 15px;
}

.eventos-pequeños {
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}

/* Cards medianas */
.evento-card-medium {
  padding: 35px 25px;
  background: white;
  border-radius: 15px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;
  height: 100%;
  border: 2px solid transparent;
}

.evento-card-medium:hover {
  transform: translateY(-8px);
  box-shadow: 0 15px 35px rgba(179, 168, 90, 0.25);
  border-color: #b3a85a;
}

.evento-card-medium h3 {
  font-size: 1.6rem;
  color: #b3a85a;
  font-weight: 600;
  margin-bottom: 20px;
}

.evento-card-medium p {
  color: #6c757d;
  line-height: 1.6;
  font-size: 0.95rem;
}

.emblema-medium {
  width: 70px;
  height: 70px;
  margin-bottom: 20px;
}

/* Responsive */
@media (max-width: 768px) {
  .main-title h1 {
    font-size: 2.5rem;
  }

  .section-title h2 {
    font-size: 2rem;
  }

  .calendar-header h3 {
    font-size: 1.5rem;
  }

  .calendar-container,
  .presagio-section,
  .encuentros-section {
    padding: 30px 20px;
  }

  .evento-card {
    padding: 30px 20px;
  }

  .evento-card h3 {
    font-size: 1.5rem;
  }

  .evento-card-large {
    padding: 30px 25px;
  }

  .evento-card-large h3 {
    font-size: 1.6rem;
  }

  .variant-item {
    padding: 15px;
  }

  .variant-item h4 {
    font-size: 1.2rem;
  }

  .evento-card-principal {
    padding: 40px 30px;
  }

  .evento-card-principal h3 {
    font-size: 2rem;
  }

  .fungi-variants-grid {
    grid-template-columns: 1fr;
    gap: 15px;
  }

  .emblema-principal {
    width: 80px;
    height: 80px;
  }

  .evento-card-small {
    padding: 20px 15px;
  }

  .evento-card-small h4 {
    font-size: 1.2rem;
  }

  .evento-card-medium {
    padding: 25px 20px;
  }

  .evento-card-medium h3 {
    font-size: 1.4rem;
  }

  .emblema-medium {
    width: 60px;
    height: 60px;
  }
}

@media (max-width: 768px) {
  .day-number {
    font-size: 0.75rem;
    top: 4px;
    left: 4px;
  }

  .event-logo {
    width: 35px;
    height: 35px;
  }

  .event-title {
    font-size: 0.7rem;
  }

  .event-subtitle,
  .event-location {
    font-size: 0.6rem;
  }

  .event-info {
    padding: 10px;
    min-width: 200px;
  }
}

@media (max-width: 480px) {
  .calendar-grid {
    gap: 5px;
  }

  .calendar-day-header {
    padding: 8px 5px;
    font-size: 0.7rem;
  }

  .day-number {
    font-size: 0.7rem;
    top: 3px;
    left: 3px;
  }

  .event-logo {
    width: 28px;
    height: 28px;
  }

  .event-title {
    font-size: 0.65rem;
    margin-bottom: 3px;
  }

  .event-subtitle,
  .event-location {
    font-size: 0.55rem;
    line-height: 1.2;
  }

  .has-event .day-number {
    font-size: 0.75rem;
  }

  .event-info {
    padding: 8px;
    min-width: 180px;
    max-width: 220px;
  }
}
</style>
